version: '3.8'

services:
  solid-oidc-provider:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - ISSUER=http://localhost:3001
      - COOKIE_SECRET=solid_oidc_dev_cookie_secret
    volumes:
      - ./keys:/app/keys
      - ./public:/app/public
    restart: unless-stopped
    stop_grace_period: 15s
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3001/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
