openapi: 3.0.3
info:
  title: Solid OIDC Provider
  version: 1.0.0
  description: Solid OIDC Provider API for the PDS3.0 project
servers:
  - url: http://localhost:3001
    description: Local development server
paths:
  /.well-known/openid-configuration:
    get:
      summary: Discover OIDC provider metadata
      responses:
        '200':
          description: Configuration document
          content:
            application/json:
              schema:
                type: object
                properties:
                  issuer:
                    type: string
                  authorization_endpoint:
                    type: string
                  token_endpoint:
                    type: string
                  userinfo_endpoint:
                    type: string
                  jwks_uri:
                    type: string
                  registration_endpoint:
                    type: string
                  response_types_supported:
                    type: array
                    items:
                      type: string
                  subject_types_supported:
                    type: array
                    items:
                      type: string
                  id_token_signing_alg_values_supported:
                    type: array
                    items:
                      type: string
                  dpop_signing_alg_values_supported:
                    type: array
                    items:
                      type: string
  /register:
    post:
      summary: Register new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                webid:
                  type: string
                  description: Optional WebID for the user
      responses:
        '201':
          description: Registered
  /authorize:
    get:
      summary: Authorize request
      parameters:
        - name: response_type
          in: query
          required: true
          schema:
            type: string
        - name: client_id
          in: query
          required: true
          schema:
            type: string
        - name: redirect_uri
          in: query
          required: true
          schema:
            type: string
        - name: scope
          in: query
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Redirect with code
  /token:
    post:
      summary: Exchange code for token
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: authorization_code
                code:
                  type: string
                redirect_uri:
                  type: string
                client_id:
                  type: string
                dpop_jkt:
                  type: string
                  description: DPoP JWK Thumbprint for proof of possession
      responses:
        '200':
          description: Token response
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  id_token:
                    type: string
                  token_type:
                    type: string
                    enum:
                      - Bearer
                      - DPoP
                  expires_in:
                    type: integer
                  refresh_token:
                    type: string
  
  /jwks.json:
    get:
      summary: Get JSON Web Key Set
      responses:
        '200':
          description: JWKS document
          content:
            application/json:
              schema:
                type: object
                properties:
                  keys:
                    type: array
                    items:
                      type: object
  
  /profile/{username}:
    get:
      summary: Get WebID profile
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: WebID profile in Turtle or JSON-LD
          content:
            text/turtle:
              schema:
                type: string
            application/ld+json:
              schema:
                type: object
    put:
      summary: Update WebID profile
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          text/turtle:
            schema:
              type: string
          application/ld+json:
            schema:
              type: object
      responses:
        '200':
          description: Updated
                    type: string
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: integer
                  id_token:
                    type: string
  /reset:
    post:
      summary: Send password reset email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Reset email sent
  /reset/{token}:
    post:
      summary: Submit new password
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
      responses:
        '200':
          description: Password reset successful
  /userinfo:
    get:
      summary: Get user information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub:
                    type: string
                  email:
                    type: string
                  webid:
                    type: string
  /jwks.json:
    get:
      summary: Get JSON Web Key Set
      responses:
        '200':
          description: JWKS for token verification
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
